### ISSUE TITLE
On-screen keyboard does not show up on login screen

### ISSUE THREAD

**Issue by jyy** [FydeOS/chromium_os-raspberry_pi#146]
**Describe your setup**
 - Raspberry Pi 4 Model B 4GB
 - Raspberry Pi 7" Touch Screen
 - Chromium OS r86 r2

**To Reproduce**
1. On login screen, tap lower right-hand corner menu to bring up Accessibility 
2. Scroll down to "On-screen keyboard" and select
3. Observe that keyboard icon shows up in bottom task bar
4. Tap keyboard icon and observe that no on-screen keyboard appears

**Expected behaviour**
I would expect that the on-screen keyboard appear

**Comment by fydeos-alpha** [comment]
it's kind of a known issue to Chromium OS, for the very initial boot you will need a physical keyboard to complete the creation of an active user. Once the user is created you may then use on-screen keyboard to login.

It's probably because Chromium OS does not know you are using a touchscreen hence it does not offer you tablet experience.
