### ISSUE TITLE
chrome://flags are missing

### ISSUE THREAD

**Issue by darkoverlordofdata** [FydeOS/chromium_os-raspberry_pi#160]
**Describe the bug or issue**
chrome://flags are missing

**Describe your setup*
rpi 400 with 4gb ram
chromiumos release r89

**To Reproduce**
start the browser, and enter chrome://flags in the address bar

**Expected behaviour**
I expect to see the experimental flags page

**Additional context**
I tried installing the latest release tagged r89 on my raspberry 400. Video update is very slow... I tried some html games and I am getting about 4 fps. The same games run at 60 fps on my old arm cpu chromebook. So I went into the browser to enable GPU on chrome://flags, and the page is blank - I see the title Experimental with the erlenmyer flask icon, but the page is blank - no flags.
How do I enable flags?

**Comment by fydeos-alpha** [comment]
This is caused by lacking the tpm device on the Raspberry Pi. In FydeOS for You - Raspberry Pi 400 we have modified Chromium code to bypass tpm check to enable chrome://flags. For Chromium OS for Raspberry Pi we want to keep Chromium as vanilla as possible. 

If you wish to change chrome://flags, try FydeOS for You - Raspberry Pi 400
