### ISSUE TITLE
“Something went wrong” screen after trying to enable debugging options in the first time setup.

### ISSUE THREAD

**Issue by Temmie72832l** [FydeOS/chromium_os-raspberry_pi#163]
**Describe the bug or issue**
“Something went wrong” screen after trying to enable debugging options in the first time setup

**Describe your setup**
 - Pi 4B 8GB RAM
 - Chromium 89.0.4389.82
 - USB 3.0 FD 32GB *booted from*
 -

**To Reproduce**
1. Boot into the first time setup
2. Click on 'Enable debugging features.'
3. See error

**Screenshots and/or hardware setup photos**
![image](https://user-images.githubusercontent.com/62681612/118043812-b618a980-b32a-11eb-9350-625fa8eecaac.jpg)
![image](https://user-images.githubusercontent.com/62681612/118043866-c892e300-b32a-11eb-8c2d-3d3c6773e38e.jpg)

**Comment by nirocfz** [comment]
There're a couple of reasons that can cause errors like this. Since the error occurred just after clicking the button, it might because of debugd(debug daemon process). 

I reproduced the error, and there's an error message in `/var/log/chrome/chrome` 

```
2021-05-13T06:01:51.779097Z ERROR chrome[1015:1015]: [object_proxy.cc(621)] Failed to call method: org.chromium.debugd.QueryDevFeatures: object_path= /org/chromium/debugd: org.chromium.debugd.error.DevFeatures: Unable to open FDT property firmware-version
```

It seems that this error is related to the firmware of the device.

The [image here](https://github.com/FydeOS/chromium_os-raspberry_pi/releases/tag/r89)  is a `dev` type image file, you can assume that the developer mode is already on, you can modify OS files, you can set a password for `chronos` or `root`, and ssh into the device.

**Comment by Temmie72832l** [comment]
Thanks i'll be sure to try that out.

**Comment by Temmie72832l** [comment]
Also what is the name of the user folder after sign in.

**Comment by Temmie72832l** [comment]
Still experiencing the same issue with the img you linked

**Comment by nirocfz** [comment]
I think you can ignore the error, you already got `debugging features`.

**Comment by Temmie72832l** [comment]
just to clarify debugging features allow you to access / in the file manager correct?

**Comment by nirocfz** [comment]
Please check the Introduction part of this page https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features
