### ISSUE TITLE
Steps for upgrading from r92 image to r96

### ISSUE THREAD

**Issue by netbug1010** [FydeOS/chromium_os-raspberry_pi#215]
I have been using the r92 image for quite a while, I am pretty satisfied with the experience. Now, with the r96 release, I am wondering if there is a way I can upgrade the OS from r92 to r96 without destroying the existing data on the SDcard.

Any help will be appreciated.

**Comment by fydeos-alpha** [comment]
You won't be able to update to r96 ***with our release image***, at least we have not found a way to do that without heavily modifying the OTA mechanism within Chromium OS and cros_sdk anyway.

You can, however, setup your own development build environment and produce a newer build yourself; then setup a [devserver](https://chromium.googlesource.com/chromiumos/chromite/+/HEAD/docs/devserver.md) instance and run it somewhere accessible from your Chromium OS image. Use the `devserver` to generate an update payload and then serve it to your Chromium OS. To break down, the steps are:

 - Follow the README of this project and make your own build, for example r96 at the time when this comment was written
 - Setup the [devserver](https://chromium.googlesource.com/chromiumos/chromite/+/HEAD/docs/devserver.md) and spin it up
 - Modify your current Chromium OS `/etc/lsb-release` file and edit the update server URL to point to your local devserver
 - Use devserver commands to generate a `update.gz` payload from your successful build
 - Wire things together so that your Chromium OS can update via your local devserver

It's not very hard indeed, however, if you do find this tedious, FydeOS for You - Raspberry Pi 400 does that all for you, at a small cost.

**Comment by netbug1010** [comment]
Thanks!
