### ISSUE TITLE
System file size allocation too large. Unable to load linux environment or download apps

### ISSUE THREAD

**Issue by Namrepus221** [FydeOS/chromium_os-raspberry_pi#245]
I'm trying to run ChromiumOS with a Raspberry Pi and have a 256gb SD Card. When I attempt to load the Linux environment it immediately fails because I have a System file of 253gb and only 3 GB of "free" space available.

How do I shrink the size of the system file when it's written so I don't use 99% of it on useless stuff?

I am also aware of issue #111 but it keeps saying that the is is not running on removable storage and will not expand the file system,

**Comment by Namrepus221** [comment]
![image](https://user-images.githubusercontent.com/88173498/232365785-5e97dc10-969d-41bc-af07-442a1be09272.jpeg)

**Comment by Damenly** [comment]
It's a known bug which will be fixed in next release. 
For current version, you can slove it in:
1. back up your data first 
2. follow https://faq.fydeos.com/en/getting-started/shell-access/
3. call `mount -oremount,rw /`
4. call `echo "echo yes" > /usr/sbin/is_running_from_installer`
5. call `chmod +x /usr/sbin/is_running_from_installer`
6. call `/usr/sbin/expand-partition.sh -d $(findmnt -n -o source /mnt/stateful_partition)`
7. reboot
